version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - apps/backend/.env
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        # Change this if deploying behind a reverse proxy
        VITE_API_URL: http://localhost:3000
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

